name: Deploy Angular to GitHub Pages

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: "24"
      base_href:
        required: true
        type: string
      publish_dir:
        required: true
        type: string
    secrets:
      github_token:
        required: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Instalar dependencias
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production --base-href "${{ inputs.base_href }}"

      - name: Copiar index.html a 404.html
        run: |
          cp ${{ inputs.publish_dir }}/index.html \
             ${{ inputs.publish_dir }}/404.html

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ${{ inputs.publish_dir }}