name: Deploy Angular to GitHub Pages

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: "."

      base_href:
        required: true
        type: string

      publish_dir:
        required: true
        type: string

      environment_keys:
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: RobertoVillalon/infraestructura
          path: infra

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalar dependencias
        working-directory: ${{ inputs.working_directory }}
        run: npm ci

      - name: Crear Environment.ts
        if: ${{ inputs.environment_keys != '' }}
        working-directory: ${{ inputs.working_directory }}
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
          ENV_KEYS: ${{ inputs.environment_keys }}
        run: bash scripts/generate-angular-env.sh

      - name: Build Angular
        working-directory: ${{ inputs.working_directory }}
        run: npm run build -- --configuration production --base-href "${{ inputs.base_href }}"

      - name: Copiar index.html a 404.html
        run: |
          cp ${{ inputs.publish_dir }}/index.html \
             ${{ inputs.publish_dir }}/404.html

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish_dir }}
