name: Test Functionabilities

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug available secrets
      env:
        SECRETS_JSON: ${{ toJSON(secrets) }}
    
      run: |
        echo "$SECRETS_JSON" | jq 'keys'
